### ISSUE TITLE
Add an option to render with your reserved name instead of 'smurf' names.

### ISSUE THREAD

**Issue by nrabins** [ballparts/TagProReplays#8]
This would be useful for situations where you don't want to reveal your smurf names or where you want to add continuity to replays.

**Comment by ballparts** [comment]
I will not be implementing this, because I want the replays to be an accurate representation of what happened in the match with the exception of aesthetic things like texture pack. The name a player chooses to use in-game does have an effect on how that player is perceived by other players and consequently how those other players play.

**Comment by nrabins** [comment]
That's reasonable. I wouldn't be doing this myself, as my smurf names are awesome as well as funky fresh, but I thought some people might be interested in it.
